export const getEmailTemplate = (data: { name: string, email: string, phone: string, service: string, brand: string, message: string }) => {
    const { name, email, phone, service, brand, message } = data;

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: #050505;
                color: #ffffff;
                margin: 0;
                padding: 0;
            }
            .container {
                max-width: 600px;
                margin: 20px auto;
                background: #0d0d0d;
                border: 1px solid #1a1a1a;
                border-radius: 12px;
                overflow: hidden;
            }
            .header {
                background: linear-gradient(90deg, #6d28d9, #3b82f6);
                padding: 30px;
                text-align: center;
            }
            .header h1 {
                margin: 0;
                font-size: 24px;
                letter-spacing: 2px;
                text-transform: uppercase;
            }
            .content {
                padding: 40px;
            }
            .item {
                margin-bottom: 25px;
            }
            .label {
                color: #d4af37;
                font-size: 12px;
                text-transform: uppercase;
                letter-spacing: 1.5px;
                margin-bottom: 5px;
            }
            .value {
                font-size: 16px;
                color: #e0e0e0;
                font-weight: 500;
            }
            .message-box {
                background: #151515;
                padding: 15px;
                border-radius: 8px;
                border-left: 3px solid #6d28d9;
                margin-top: 10px;
            }
            .footer {
                padding: 20px;
                text-align: center;
                background: #0a0a0a;
                border-top: 1px solid #1a1a1a;
                color: #555;
                font-size: 12px;
            }
            .accent {
                color: #3b82f6;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>nooh<span class="accent">Ark</span> Connection</h1>
            </div>
            <div class="content">
                <div class="item">
                    <div class="label">Origin Voyager</div>
                    <div class="value">${name}</div>
                </div>
                <div class="item">
                    <div class="label">Secure Email</div>
                    <div class="value">${email}</div>
                </div>
                <div class="item">
                    <div class="label">Communication Line</div>
                    <div class="value">${phone || "Not specified"}</div>
                </div>
                <div class="item">
                    <div class="label">Targeted Module</div>
                    <div class="value">${service}</div>
                </div>
                <div class="item">
                    <div class="label">Brand Identity</div>
                    <div class="value">${brand}</div>
                </div>
                <div class="item">
                    <div class="label">Transmission Brief</div>
                    <div class="message-box">
                        ${message || "No additional message."}
                    </div>
                </div>
            </div>
            <div class="footer">
                Transmission generated by noohArk Orbital Terminal &copy; 2026
            </div>
        </div>
    </body>
    </html>
    `;
};
